[SERVICE]
    Flush        1
    Log_Level    info
    Parsers_File parsers.conf

# Terima log dari Docker (logging driver: fluentd) di port 24224
[INPUT]
    Name   forward
    Listen 0.0.0.0
    Port   24224

# Pecah isi field "log" (JSON dari aplikasi) jadi field terpisah:
# level, service, message, ts
[FILTER]
    Name         parser
    Match        *
    Key_Name     log
    Parser       json
    Reserve_Data On

# Kirim ke Elasticsearch (Lab 1) lewat port host, index: app-logs
[OUTPUT]
    Name               es
    Match              *
    Host               host.docker.internal
    Port               9200
    Index              app-logs
    Suppress_Type_Name On
    Logstash_Format    Off
    Retry_Limit        False
